### ISSUE TITLE
Implement Additional Pages/Add More Content

### ISSUE THREAD

**Issue by majordwarf** [MovingBlocks/movingblocks.github.com#17]
For Hacktoberfest - _Register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) before submitting a Pull Request_

----------------

For time being the core website is working as expected but most of the pages seems like desert. It'd be good to add some content on the already existing pages or create new pages if required to bring the project to life. 

You may refer to the current splash site for the inspiration and content, [Terasology](https://terasology.org).

| Page Name | Create Page | Add Content |
|---|---|---|
| Index/Home | :heavy_check_mark: | :heavy_check_mark: |
| About Game | :heavy_check_mark: | :heavy_check_mark: |
| Media | :heavy_check_mark: | :heavy_check_mark: |

**_Edit 1_**: ~~Media page is now present along with some base content with merge of #17 . Still needs a proper gallery implementation to be considered complete. Thus it's still marked WIP.~~

**_Edit 2_**: All the tasks seems completed.

**Comment by dipanshu231099** [comment]
@majordwarf i would like to work on it

**Comment by majordwarf** [comment]
> @majordwarf i would like to work on it

Sure! Go ahead, if you have any doubts you can ask here or join our discord - [Invite Link](https://discord.gg/terasology)

**Comment by clc80** [comment]
@majordwarf Can I work on this as well?

**Comment by majordwarf** [comment]
**_Issue seems to have completed being fixed/implemented. Closing the issue based on it's status._**
