### ISSUE TITLE
Implement Gallery Component to be used in Media Page

### ISSUE THREAD

**Issue by majordwarf** [MovingBlocks/movingblocks.github.com#18]
For Hacktoberfest - _Register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) before submitting a Pull Request_

----------------

Create a image gallery as a react component to be used in the media page to display the game screenshots. The component should fetch images from a certain folder insider the `static`directory and display them. The gallery should be easy to navigate and responsive. The current splash site's galley lies here - [Gallery](https://terasology.org/gallery.html)

_It'd be also nice if we can somehow add videos to the gallery too._

**Comment by clc80** [comment]
@majordwarf Can I take this on?

**Comment by endurance21** [comment]
hey !
@majordwarf 
I am new here , i  was just crawling the website and got to this issue,  i think we do have `Gallery` component that uses Graphql to query the images from static/images dirctory https://github.com/MovingBlocks/ModuleSite/blob/master/src/components/Media/Media.jsx

Also , as i can see the gallery is responsive to almost every scrensize and zooming feature is also loking fine.

Is there else thing to be incorporated into it ?

**Comment by majordwarf** [comment]
The current gallery feels very outdated and the development server breaks on windows. So we're looking into refactoring the current page or making it from the ground up.

**Comment by Pjha72** [comment]
@majordwarf pls tell me what the refactoring of the current page.
Pls assign me

**Comment by jdrueckert** [comment]
Hi @Pjha72 
Actually, this issue is going to be resolved by #180 (currently in review) - not with a hand-made Gallery component but using reactstrap's `Carousel`. So there's no real action item here anymore, sorry.
