### ISSUE TITLE
The project won't build on windows 11

### ISSUE THREAD

**Issue by Rukki13** [MovingBlocks/movingblocks.github.com#236]
The commands `yarn run build` and `yarn run develop` don't work because of this command in _package.json_: 
`"build": "NODE_OPTIONS=\"--no-experimental-fetch\" gatsby build"`
It's trying to set the environment variable incorrectly, and to fix it, it must be changed to:
`"build": "set NODE_OPTIONS=--no-experimental-fetch && gatsby build"`
Nearly the same goes for `yarn run develop`

**Comment by Rukki13** [comment]
I've fixed it and made a pull request => #237

**Comment by jdrueckert** [comment]
Fixed by #237
