### ISSUE TITLE
Action Items for Website Replacement

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/movingblocks.github.com#34]
In its current state, the ModuleSite looks like a half-done replacement for our current website.
According to @majordwarf the ModuleSite being built with Gatsby was a deliberate decision based on the perception of Gatsby as more future-proof than Jekyll which our current website is based on.
_If_ we decide to replace our current website with the module site, the following action items would need to be done in order to switch without losing any functionality we currently have in our website.

# Action Items

## Additions
- [x] Migrate blog posts from website
- [x] Add missing project info from website
- [x] Add link to Adventure Site
- [x] Add OS selection to download page
- [x] Migrate GSoC Mentor Trello integration from Website
- [x] Add Patreon link to footer

Update (Dec 30, 2022):
- [x] Migrate [missing blog post](https://terasology.org/2021/09/11/teraspotlight-gsoc-2021-summary.html) from website
- [x] Migrate missing gallery images from website

## Fixes
- [x] Fix low res images on Project Info page ("The Game")
- [x] Fix blog post linking issues on homepage
- [x] Remove "Contact us" page
- [x] Fix download link
- [x] Fix colors [hove color on buttons can be too much bright, at least on my screen]

Update (Dec 30, 2022)
- [x] Fix blog search results message "Found ... _modules_ ..."
- [x] Fix blog search result order (newest blogs should show up first)
- [x] Fix home page video aspect ratio
- [x] Modules: Fix duplicated banner in module post for modules with custom banner

## Improvements
- [x] Gallery/media section
- [x] Theme the site according to Terasology looks (colors, gooeys, etc.)

Update (Dec 30, 2022)
- [x] Integrate [banner image](https://terasology.org/img/ss_6.jpg) from website 
- [x] Invert screenshot order (newest should be shown first)
- [x] Add additional screenshots
- [x] Align card content (especially for module cards) at top - currently aligned center if short description text
- [X] Document (in engine wiki) how to create a new blog post on modulesite for blog authors (https://github.com/MovingBlocks/Terasology/wiki/Outreach)
- [x] Fetch modules data from GitHub
- [x] Overhaul Gallery
- [x] Paginate modules by first letter
- [x] Reduce cover image duplication

## Switch
- [x] Host module site via Github Pages
- [x] Switch terasology.org to point to module site instead.

**Comment by jdrueckert** [comment]
FYI: @majordwarf @pollend @TheShubham99 @stefaniamak @Cervator @skaldarnar

**Comment by jdrueckert** [comment]
remaining open tasks (except for the switch itself) are not mandatory but rather "wanna do"s. moving this issue to the "[Feature & Content Additions](https://github.com/MovingBlocks/ModuleSite/milestone/3)" milestone

**Comment by skaldarnar** [comment]
Closing as completed.
