### ISSUE TITLE
ambigous text on `gooey example` post 

### ISSUE THREAD

**Issue by endurance21** [MovingBlocks/movingblocks.github.com#40]
In the righmost side of  the Post header componet , It seems `hello` keyword has been mistakenly put there !
![image](https://user-images.githubusercontent.com/43696525/108253825-38585e00-7180-11eb-9a86-f4677cb82a9f.png)

**Comment by endurance21** [comment]
@majordwarf  
can you please guide  from where this post data is coming from and if it is necessary to fix this one?

**Comment by majordwarf** [comment]
Hey.

This website currently isn't being used in production. The data you see inside `/module` is just a boilerplate. The module site is intended to make all the modules of the Terasoloy easily accessible to the public, all these modules reside under "[Terasology](https://github.com/Terasology)" org on GitHub.

When the website will go into production, it'll be automated via a CI/CD pipeline. A basic structure of the pipeline will be to fetch all the repositories from Terasology org, identify if the repo is a module or no. If the repo is a module, extract metadata that could be used to generate the page for the module itself (README.md, logo, cover image, info from module.txt). Use that data to generate the page.

So, when the website will be deployed, the boilerplate data will be cleared and the newly generated data would be placed. Hope this clears your confusion! 😄

**Comment by endurance21** [comment]
Okay !
it make sense !
I am closing this issue then !
