### ISSUE TITLE
GitHub actions ( build checks ) 

### ISSUE THREAD

**Issue by endurance21** [MovingBlocks/movingblocks.github.com#41]
## New feature 
- GitHub actions can be very useful to check build process on every commit or pull request .
- It would be a script that will be present in .GitHub/workflows folder
- I would like to work on this issue .

**Comment by endurance21** [comment]
@majordwarf shall i raise a pr for the same ?

**Comment by majordwarf** [comment]
What things do you plan on testing via GH Actions?

**Comment by endurance21** [comment]
for now it would be simply build pass ( like it github actions will show if the current commit done to the repo is breaking the build process  or not ) it is highly useful to see which commit id breakingh the build process of website .
More advanced checks would be using unit testing on github servers too( in future if unit test are to be written for react componet and server apis )

**Comment by jdrueckert** [comment]
done
